spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      schema-locations: classpath:schema.sql
server:
  error:
    include-message: always
